#!/bin/bash

export TEMPLATECONF=$(pwd)/sources/meta-piosk/conf/templates/piosk
source $(pwd)/sources/poky/oe-init-build-env build

if [[ ! -L "./conf/bblayers.conf" ]]; then
    rm -rf ./conf/bblayers.conf ./conf/local.conf
    ln -s $TEMPLATECONF/bblayers.conf.sample ./conf/bblayers.conf
    ln -s $TEMPLATECONF/local.conf.sample ./conf/local.conf
fi